# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'palletize.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 647)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 280, 381, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        self.reset_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout.addWidget(self.reset_btn)
        self.show_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.show_btn.setObjectName("show_btn")
        self.horizontalLayout.addWidget(self.show_btn)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(510, 60, 451, 541))
        self.tableView.setObjectName("tableView")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(470, 10, 21, 601))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(510, 20, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 201, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 171, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.plt_length = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.plt_length.setObjectName("plt_length")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.plt_length)
        self.line_3 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.plt_width = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.plt_width.setObjectName("plt_width")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.plt_width)
        self.line_2 = QtWidgets.QFrame(self.formLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_2)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.plt_height = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.plt_height.setObjectName("plt_height")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.plt_height)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 50, 191, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTabletTracking(True)
        self.groupBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 21, 161, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.ctn_length = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ctn_length.setObjectName("ctn_length")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ctn_length)
        self.line_5 = QtWidgets.QFrame(self.formLayoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_5)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.ctn_width = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ctn_width.setObjectName("ctn_width")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ctn_width)
        self.line_4 = QtWidgets.QFrame(self.formLayoutWidget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.line_4)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.ctn_height = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ctn_height.setObjectName("ctn_height")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ctn_height)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 200, 411, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_3.setObjectName("groupBox_3")
        self.resultText1 = QtWidgets.QTextEdit(self.groupBox_3)
        self.resultText1.setGeometry(QtCore.QRect(20, 20, 381, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultText1.sizePolicy().hasHeightForWidth())
        self.resultText1.setSizePolicy(sizePolicy)
        self.resultText1.setObjectName("resultText1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 350, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 480, 421, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.input_hint = QtWidgets.QLabel(self.groupBox_4)
        self.input_hint.setEnabled(True)
        self.input_hint.setGeometry(QtCore.QRect(20, 20, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_hint.setFont(font)
        self.input_hint.setMouseTracking(False)
        self.input_hint.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_hint.setObjectName("input_hint")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 90, 381, 22))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.length_col = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.length_col.setObjectName("length_col")
        self.horizontalLayout_2.addWidget(self.length_col)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.width_col = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.width_col.setObjectName("width_col")
        self.horizontalLayout_2.addWidget(self.width_col)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.height_col = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.height_col.setObjectName("height_col")
        self.horizontalLayout_2.addWidget(self.height_col)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_2.addWidget(self.label_16)
        self.carton_col = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.carton_col.setObjectName("carton_col")
        self.horizontalLayout_2.addWidget(self.carton_col)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 50, 191, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.cm_radiobtn = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.cm_radiobtn.setChecked(True)
        self.cm_radiobtn.setObjectName("cm_radiobtn")
        self.horizontalLayout_3.addWidget(self.cm_radiobtn)
        self.mm_radiobtn = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.mm_radiobtn.setObjectName("mm_radiobtn")
        self.horizontalLayout_3.addWidget(self.mm_radiobtn)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 320, 481, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 380, 421, 91))
        self.groupBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 381, 54))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.upload_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.upload_btn.setObjectName("upload_btn")
        self.gridLayout.addWidget(self.upload_btn, 0, 0, 1, 1)
        self.process_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.process_btn.setObjectName("process_btn")
        self.gridLayout.addWidget(self.process_btn, 0, 1, 1, 1)
        self.download_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.download_btn.setObjectName("download_btn")
        self.gridLayout.addWidget(self.download_btn, 1, 0, 1, 1)
        self.clearall_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.clearall_btn.setObjectName("clearall_btn")
        self.gridLayout.addWidget(self.clearall_btn, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setCheckable(True)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.plt_length, self.plt_width)
        MainWindow.setTabOrder(self.plt_width, self.plt_height)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ok_btn.setText(_translate("MainWindow", "确定"))
        self.reset_btn.setText(_translate("MainWindow", "重置"))
        self.show_btn.setText(_translate("MainWindow", "垛型预览"))
        self.label_11.setText(_translate("MainWindow", "数据预览"))
        self.groupBox.setTitle(_translate("MainWindow", "托规"))
        self.plt_length.setText(_translate("MainWindow", "120"))
        self.label_4.setText(_translate("MainWindow", "托盘宽(cm)"))
        self.plt_width.setText(_translate("MainWindow", "100"))
        self.label_5.setText(_translate("MainWindow", "托盘高(cm)"))
        self.plt_height.setText(_translate("MainWindow", "160"))
        self.label_3.setText(_translate("MainWindow", "托盘长(cm)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "箱规"))
        self.ctn_length.setText(_translate("MainWindow", "40"))
        self.label_7.setText(_translate("MainWindow", "箱宽(cm)"))
        self.ctn_width.setText(_translate("MainWindow", "30"))
        self.label_8.setText(_translate("MainWindow", "箱高(cm)"))
        self.ctn_height.setText(_translate("MainWindow", "30"))
        self.label_6.setText(_translate("MainWindow", "箱长(cm)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "结果显示"))
        self.label.setText(_translate("MainWindow", "单SKU分析"))
        self.label_2.setText(_translate("MainWindow", "批量分析"))
        self.groupBox_4.setTitle(_translate("MainWindow", "数据选取"))
        self.input_hint.setText(_translate("MainWindow", "填写导入数据对应的列编号(从0开始）"))
        self.label_13.setText(_translate("MainWindow", "箱长"))
        self.label_14.setText(_translate("MainWindow", "箱宽"))
        self.label_15.setText(_translate("MainWindow", "箱高"))
        self.label_16.setText(_translate("MainWindow", "箱数"))
        self.label_9.setText(_translate("MainWindow", "单位："))
        self.cm_radiobtn.setText(_translate("MainWindow", "cm"))
        self.mm_radiobtn.setText(_translate("MainWindow", "mm"))
        self.groupBox_5.setTitle(_translate("MainWindow", "数据操作"))
        self.upload_btn.setText(_translate("MainWindow", "数据导入"))
        self.process_btn.setText(_translate("MainWindow", "数据处理"))
        self.download_btn.setText(_translate("MainWindow", "数据导出"))
        self.clearall_btn.setText(_translate("MainWindow", "清除重置"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate("MainWindow", "新建"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))

