# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'palletize.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(7, 56, 125);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 4, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.gridLayout_7.addWidget(self.tableView, 8, 0, 1, 5)
        self.temp2 = QtWidgets.QLabel(self.centralwidget)
        self.temp2.setText("")
        self.temp2.setObjectName("temp2")
        self.gridLayout_7.addWidget(self.temp2, 4, 0, 2, 2)
        self.temp1 = QtWidgets.QLabel(self.centralwidget)
        self.temp1.setText("")
        self.temp1.setObjectName("temp1")
        self.gridLayout_7.addWidget(self.temp1, 1, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_hint = QtWidgets.QLabel(self.groupBox_4)
        self.input_hint.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_hint.sizePolicy().hasHeightForWidth())
        self.input_hint.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_hint.setFont(font)
        self.input_hint.setMouseTracking(True)
        self.input_hint.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.input_hint.setTextFormat(QtCore.Qt.RichText)
        self.input_hint.setScaledContents(False)
        self.input_hint.setObjectName("input_hint")
        self.gridLayout_2.addWidget(self.input_hint, 0, 0, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.weightUnit_label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weightUnit_label.sizePolicy().hasHeightForWidth())
        self.weightUnit_label.setSizePolicy(sizePolicy)
        self.weightUnit_label.setObjectName("weightUnit_label")
        self.horizontalLayout_6.addWidget(self.weightUnit_label)
        self.kg_radio_btn = QtWidgets.QRadioButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kg_radio_btn.sizePolicy().hasHeightForWidth())
        self.kg_radio_btn.setSizePolicy(sizePolicy)
        self.kg_radio_btn.setChecked(True)
        self.kg_radio_btn.setObjectName("kg_radio_btn")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.kg_radio_btn)
        self.horizontalLayout_6.addWidget(self.kg_radio_btn)
        self.g_radio_btn = QtWidgets.QRadioButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_radio_btn.sizePolicy().hasHeightForWidth())
        self.g_radio_btn.setSizePolicy(sizePolicy)
        self.g_radio_btn.setObjectName("g_radio_btn")
        self.buttonGroup.addButton(self.g_radio_btn)
        self.horizontalLayout_6.addWidget(self.g_radio_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lengthUnit_label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lengthUnit_label.sizePolicy().hasHeightForWidth())
        self.lengthUnit_label.setSizePolicy(sizePolicy)
        self.lengthUnit_label.setObjectName("lengthUnit_label")
        self.horizontalLayout_3.addWidget(self.lengthUnit_label)
        self.cm_radio_btn = QtWidgets.QRadioButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cm_radio_btn.sizePolicy().hasHeightForWidth())
        self.cm_radio_btn.setSizePolicy(sizePolicy)
        self.cm_radio_btn.setChecked(True)
        self.cm_radio_btn.setAutoExclusive(True)
        self.cm_radio_btn.setObjectName("cm_radio_btn")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.cm_radio_btn)
        self.horizontalLayout_3.addWidget(self.cm_radio_btn)
        self.mm_radio_btn = QtWidgets.QRadioButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mm_radio_btn.sizePolicy().hasHeightForWidth())
        self.mm_radio_btn.setSizePolicy(sizePolicy)
        self.mm_radio_btn.setObjectName("mm_radio_btn")
        self.buttonGroup_2.addButton(self.mm_radio_btn)
        self.horizontalLayout_3.addWidget(self.mm_radio_btn)
        self.horizontalLayout_3.setStretch(0, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.length_label = QtWidgets.QLabel(self.groupBox_4)
        self.length_label.setObjectName("length_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.length_label)
        self.length_col = QtWidgets.QLineEdit(self.groupBox_4)
        self.length_col.setObjectName("length_col")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.length_col)
        self.width_col_label = QtWidgets.QLabel(self.groupBox_4)
        self.width_col_label.setObjectName("width_col_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.width_col_label)
        self.width_col = QtWidgets.QLineEdit(self.groupBox_4)
        self.width_col.setObjectName("width_col")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.width_col)
        self.height_label = QtWidgets.QLabel(self.groupBox_4)
        self.height_label.setObjectName("height_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.height_label)
        self.height_col = QtWidgets.QLineEdit(self.groupBox_4)
        self.height_col.setObjectName("height_col")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.height_col)
        self.cartonNum_label = QtWidgets.QLabel(self.groupBox_4)
        self.cartonNum_label.setObjectName("cartonNum_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.cartonNum_label)
        self.cartonNum_col = QtWidgets.QLineEdit(self.groupBox_4)
        self.cartonNum_col.setObjectName("cartonNum_col")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cartonNum_col)
        self.gridLayout_2.addLayout(self.formLayout, 2, 0, 4, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.sku_wt_label = QtWidgets.QLabel(self.groupBox_4)
        self.sku_wt_label.setObjectName("sku_wt_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sku_wt_label)
        self.sku_wt_col = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sku_wt_col.sizePolicy().hasHeightForWidth())
        self.sku_wt_col.setSizePolicy(sizePolicy)
        self.sku_wt_col.setObjectName("sku_wt_col")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sku_wt_col)
        self.fullCartonQty_label = QtWidgets.QLabel(self.groupBox_4)
        self.fullCartonQty_label.setObjectName("fullCartonQty_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fullCartonQty_label)
        self.fullCartonQty_col = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fullCartonQty_col.sizePolicy().hasHeightForWidth())
        self.fullCartonQty_col.setSizePolicy(sizePolicy)
        self.fullCartonQty_col.setObjectName("fullCartonQty_col")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fullCartonQty_col)
        self.ctn_wt_col = QtWidgets.QLineEdit(self.groupBox_4)
        self.ctn_wt_col.setObjectName("ctn_wt_col")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ctn_wt_col)
        self.ctn_wt_label = QtWidgets.QLabel(self.groupBox_4)
        self.ctn_wt_label.setObjectName("ctn_wt_label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ctn_wt_label)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.gridLayout_2.addLayout(self.formLayout_2, 2, 1, 4, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 2, 4, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_8.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.plt_height = QtWidgets.QLineEdit(self.frame)
        self.plt_height.setObjectName("plt_height")
        self.gridLayout_5.addWidget(self.plt_height, 2, 1, 1, 1)
        self.plt_width = QtWidgets.QLineEdit(self.frame)
        self.plt_width.setObjectName("plt_width")
        self.gridLayout_5.addWidget(self.plt_width, 1, 1, 1, 1)
        self.plt_length = QtWidgets.QLineEdit(self.frame)
        self.plt_length.setObjectName("plt_length")
        self.gridLayout_5.addWidget(self.plt_length, 0, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.frame)
        self.gridLayout_7.addWidget(self.groupBox, 2, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTabletTracking(True)
        self.groupBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame1 = QtWidgets.QFrame(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1.sizePolicy().hasHeightForWidth())
        self.frame1.setSizePolicy(sizePolicy)
        self.frame1.setObjectName("frame1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ctn_length_label = QtWidgets.QLabel(self.frame1)
        self.ctn_length_label.setObjectName("ctn_length_label")
        self.gridLayout_4.addWidget(self.ctn_length_label, 0, 0, 1, 1)
        self.ctn_length = QtWidgets.QLineEdit(self.frame1)
        self.ctn_length.setObjectName("ctn_length")
        self.gridLayout_4.addWidget(self.ctn_length, 0, 1, 1, 1)
        self.ctn_width_label = QtWidgets.QLabel(self.frame1)
        self.ctn_width_label.setObjectName("ctn_width_label")
        self.gridLayout_4.addWidget(self.ctn_width_label, 1, 0, 1, 1)
        self.ctn_width = QtWidgets.QLineEdit(self.frame1)
        self.ctn_width.setObjectName("ctn_width")
        self.gridLayout_4.addWidget(self.ctn_width, 1, 1, 1, 1)
        self.ctn_height_label = QtWidgets.QLabel(self.frame1)
        self.ctn_height_label.setObjectName("ctn_height_label")
        self.gridLayout_4.addWidget(self.ctn_height_label, 2, 0, 1, 1)
        self.ctn_height = QtWidgets.QLineEdit(self.frame1)
        self.ctn_height.setObjectName("ctn_height")
        self.gridLayout_4.addWidget(self.ctn_height, 2, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame1)
        self.gridLayout_7.addWidget(self.groupBox_2, 2, 2, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setTabletTracking(True)
        self.groupBox_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame2 = QtWidgets.QFrame(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setObjectName("frame2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_18 = QtWidgets.QLabel(self.frame2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)
        self.plt_l_gap = QtWidgets.QLineEdit(self.frame2)
        self.plt_l_gap.setObjectName("plt_l_gap")
        self.gridLayout_3.addWidget(self.plt_l_gap, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.plt_w_gap = QtWidgets.QLineEdit(self.frame2)
        self.plt_w_gap.setObjectName("plt_w_gap")
        self.gridLayout_3.addWidget(self.plt_w_gap, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.ctn_gap = QtWidgets.QLineEdit(self.frame2)
        self.ctn_gap.setObjectName("ctn_gap")
        self.gridLayout_3.addWidget(self.ctn_gap, 2, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame2)
        self.gridLayout_7.addWidget(self.groupBox_6, 2, 3, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.download_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.download_btn.setObjectName("download_btn")
        self.gridLayout.addWidget(self.download_btn, 1, 0, 1, 1)
        self.process_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.process_btn.setObjectName("process_btn")
        self.gridLayout.addWidget(self.process_btn, 0, 1, 1, 1)
        self.upload_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.upload_btn.setObjectName("upload_btn")
        self.gridLayout.addWidget(self.upload_btn, 0, 0, 1, 1)
        self.clearall_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.clearall_btn.setObjectName("clearall_btn")
        self.gridLayout.addWidget(self.clearall_btn, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.gridLayout_7.addWidget(self.groupBox_5, 3, 4, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resultText1 = QtWidgets.QTextEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultText1.sizePolicy().hasHeightForWidth())
        self.resultText1.setSizePolicy(sizePolicy)
        self.resultText1.setObjectName("resultText1")
        self.verticalLayout.addWidget(self.resultText1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        self.reset_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout.addWidget(self.reset_btn)
        self.show_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.show_btn.setObjectName("show_btn")
        self.horizontalLayout.addWidget(self.show_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_7.addWidget(self.groupBox_3, 3, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(7, 56, 125);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(7, 56, 125);\n"
"font: 75 14pt \"微软雅黑\";")
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 6, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setCheckable(True)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.plt_length, self.plt_width)
        MainWindow.setTabOrder(self.plt_width, self.plt_height)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#07387d;\">批量分析</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "数据选取"))
        self.input_hint.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#db4614;\">填写导入数据对应的列编号(从0开始）</span></p></body></html>"))
        self.weightUnit_label.setText(_translate("MainWindow", "重量单位："))
        self.kg_radio_btn.setText(_translate("MainWindow", "kg"))
        self.g_radio_btn.setText(_translate("MainWindow", "g"))
        self.lengthUnit_label.setText(_translate("MainWindow", "长度单位："))
        self.cm_radio_btn.setText(_translate("MainWindow", "cm"))
        self.mm_radio_btn.setText(_translate("MainWindow", "mm"))
        self.length_label.setText(_translate("MainWindow", "箱长"))
        self.width_col_label.setText(_translate("MainWindow", "箱宽"))
        self.height_label.setText(_translate("MainWindow", "箱高"))
        self.cartonNum_label.setText(_translate("MainWindow", "箱数"))
        self.sku_wt_label.setText(_translate("MainWindow", "单SKU重"))
        self.fullCartonQty_label.setText(_translate("MainWindow", "箱规(件)"))
        self.ctn_wt_label.setText(_translate("MainWindow", "箱   重"))
        self.label_6.setText(_translate("MainWindow", "OR"))
        self.groupBox.setTitle(_translate("MainWindow", "托规"))
        self.label_3.setText(_translate("MainWindow", "托盘长(cm)"))
        self.label_4.setText(_translate("MainWindow", "托盘宽(cm)"))
        self.label_5.setText(_translate("MainWindow", "托盘高(cm)"))
        self.plt_height.setText(_translate("MainWindow", "160"))
        self.plt_width.setText(_translate("MainWindow", "100"))
        self.plt_length.setText(_translate("MainWindow", "120"))
        self.groupBox_2.setTitle(_translate("MainWindow", "箱规"))
        self.ctn_length_label.setText(_translate("MainWindow", "箱长(cm)"))
        self.ctn_length.setText(_translate("MainWindow", "40"))
        self.ctn_width_label.setText(_translate("MainWindow", "箱宽(cm)"))
        self.ctn_width.setText(_translate("MainWindow", "30"))
        self.ctn_height_label.setText(_translate("MainWindow", "箱高(cm)"))
        self.ctn_height.setText(_translate("MainWindow", "30"))
        self.groupBox_6.setTitle(_translate("MainWindow", "垛型"))
        self.label_18.setText(_translate("MainWindow", "托长边距(cm)"))
        self.plt_l_gap.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "托宽边距(cm)"))
        self.plt_w_gap.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "箱间距(cm）"))
        self.ctn_gap.setText(_translate("MainWindow", "0"))
        self.groupBox_5.setTitle(_translate("MainWindow", "数据操作"))
        self.download_btn.setText(_translate("MainWindow", "数据导出"))
        self.process_btn.setText(_translate("MainWindow", "数据处理"))
        self.upload_btn.setText(_translate("MainWindow", "数据导入"))
        self.clearall_btn.setText(_translate("MainWindow", "清除重置"))
        self.groupBox_3.setTitle(_translate("MainWindow", "结果显示"))
        self.ok_btn.setText(_translate("MainWindow", "确定"))
        self.reset_btn.setText(_translate("MainWindow", "重置"))
        self.show_btn.setText(_translate("MainWindow", "垛型预览"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#07387d;\">单SKU分析</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#07387d;\">数据预览</span></p></body></html>"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate("MainWindow", "新建"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))

